/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PMTD.CRM;

/**
 *
 * @author WIMBER
 */


import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.clipsrules.jni.Environment;
import net.sf.clipsrules.jni.FactAddressValue;
import net.sf.clipsrules.jni.MultifieldValue;


public class EvImp extends javax.swing.JDialog {

    /**
     * Creates new form EvImp
     */
    Environment clips;
    public EvImp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        clips = new Environment();
        clips.load("ejemplo.CLP");
        clips.reset();
        clips.run();
        try{
            String evaluar = "(find-all-facts ((?x nodo-pregunta-respuesta )) TRUE)";
            FactAddressValue value = (FactAddressValue) ((MultifieldValue) clips.eval(evaluar)).get(0);
            String valor = value.getFactSlot("valor").toString();
            System.out.println(valor);
            lblPregunta.setText(valor);
            lblRespuesta.setText("");
        }catch (Exception ex) {
            Logger.getLogger(EvProb.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblRespuesta = new javax.swing.JLabel();
        rbtnSi = new javax.swing.JRadioButton();
        rbtnNo = new javax.swing.JRadioButton();
        btnContinuar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        res = new java.awt.TextField();
        lblPregunta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRespuesta.setText("jLabel1");
        jPanel1.add(lblRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        buttonGroup1.add(rbtnSi);
        rbtnSi.setText("Si");
        rbtnSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSiActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 22));

        buttonGroup1.add(rbtnNo);
        rbtnNo.setText("No");
        jPanel1.add(rbtnNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        jPanel1.add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("EVALUACIÓN DEL NIVEL DE IMPACTO");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 40));

        label1.setText("RESULTADO");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        jPanel1.add(res, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 290, 45));

        lblPregunta.setEditable(false);
        lblPregunta.setColumns(20);
        lblPregunta.setLineWrap(true);
        lblPregunta.setRows(5);
        lblPregunta.setBorder(null);
        lblPregunta.setOpaque(false);
        jPanel1.add(lblPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 300, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnSiActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        try {
            if (rbtnSi.isSelected() == true) {
                clips.eval("(assert (opcion si))");
                System.out.println("si");
            }

            if (rbtnNo.isSelected() == true) {
                clips.eval("(assert (opcion no))");
                System.out.println("no");
            }

            clips.run();

            String evaluar = "(find-all-facts ((?x nodo-pregunta-respuesta )) TRUE)";
            FactAddressValue value = (FactAddressValue) ((MultifieldValue) clips.eval(evaluar)).get(0);
            String tipo = value.getFactSlot("tipo").toString();
            System.out.println(tipo);
            String valor = value.getFactSlot("valor").toString();
            System.out.println(valor);
            if (tipo.equals("decision")) {
                lblPregunta.setText(valor);
                lblRespuesta.setText("");
            } else {
                if(tipo.equals("respuesta")){

                    lblPregunta.setText("");
                    lblRespuesta.setText("");

                    JOptionPane.showMessageDialog(null,valor , "Mensaje",JOptionPane.INFORMATION_MESSAGE);
                    res.setText(valor);
                }else{
                    //System.exit(0);
                    
                }

            }
            buttonGroup1.clearSelection();
        } catch (Exception ex) {
            Logger.getLogger(EvProb.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EvImp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EvImp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EvImp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EvImp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EvImp dialog = new EvImp(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private javax.swing.JTextArea lblPregunta;
    private javax.swing.JLabel lblRespuesta;
    private javax.swing.JRadioButton rbtnNo;
    private javax.swing.JRadioButton rbtnSi;
    private java.awt.TextField res;
    // End of variables declaration//GEN-END:variables
}
