/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PMTD.EValInicial;

import PMTD.GuiaIni;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.CardLayout;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author WIMBER
 */
public class evaInicial extends javax.swing.JDialog {

    /**
     * Creates new form evaInicial
     */
    String nombre="EvaInicial";
    
    
    public evaInicial(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    int cocientePlaneamiento = 5;
    String tituloCarta = "Planeamiento Paralelo / Regla 1/5";
    
    public String getTiempoInicial(){
        return tiempoTotalParaleloTextField.getText();
    }
    
    public int getIndexMetodo(){
        if(paraleloRadioButton.isSelected()){
            return 0;
        }
        return 1;
    }
    
    public DefaultComboBoxModel getModeloMetodo(){
        return new DefaultComboBoxModel<>(new String[]{"Paralelo", "Secuencial"});
    }
    
    public void Generar(String nombre) throws FileNotFoundException, DocumentException{
        if(!(tiempoTotalParaleloTextField.getText().isEmpty() || (jTextField22.getText().isEmpty()) || (jTextField12.getText().isEmpty()))){
            FileOutputStream archivo = new FileOutputStream(nombre + ".pdf"); 
            Document documento = new Document();
            PdfWriter.getInstance(documento, archivo);
            documento.open();
            
            Paragraph parrafo = new Paragraph("ORDEN PREPARATORIA N°1 \n\n");
            parrafo.setAlignment(1);
            documento.add(parrafo);
            
            documento.add(new Paragraph("Planteamiento Secuencial \n" + "Regla de 1/3" + "\n"));
            documento.add(new Paragraph("Tiempo Total Disponible \n" + tiempoTotalParaleloTextField.getText() + "\n"));
            documento.add(new Paragraph("Tiempo Asignado \n" + " Días: " + jTextField12.getText() + "\n" + " Horas: " + jTextField22.getText() + "\n"));
            documento.add(new Paragraph("Etapas y pasos del PMTD \n"));
            documento.add(new Paragraph("Análisis de la misión \n" + " %Planteamiento: " + jTextField16.getText() + "\n" + "Tiempo en Días: " + jTextField13.getText() + "\n" + "Tiempo en Horas: " + jTextField28.getText() + "\n"));
            documento.add(new Paragraph("Elaboración de los cursos \n" + " %Planteamiento: " + jTextField15.getText() + "\n" + "Tiempo en Días: " + jTextField24.getText() + "\n" + "Tiempo en Horas: " + jTextField31.getText() + "\n"));
            documento.add(new Paragraph("Análisis/Comparación \n" + " %Planteamiento: " + jTextField23.getText() + "\n" + "Tiempo en Días: " + jTextField26.getText() + "\n" + "Tiempo en Horas: " + jTextField30.getText() + "\n"));
            documento.add(new Paragraph("Desarrollo del Plan \n" + " %Planteamiento: " + jTextField25.getText() + "\n" + "Tiempo en Días: " + jTextField17.getText() + "\n" + "Tiempo en Horas: " + jTextField27.getText() + "\n"));
            documento.add(new Paragraph("Tiempo Total \n" + " %Planteamiento: " + jTextField18.getText() + "\n" + "Tiempo en Días: " + jTextField18.getText() + "\n" + "Tiempo en Horas: " + jTextField29.getText() + "\n"));
            documento.add(new Paragraph("Reducit el PMTD: " + jComboBox1.getSelectedItem().toString() + "\n"));
            documento.add(new Paragraph("Organizaciones a Integrar \n" + jTextField20.getText() + "\n"));

            //documento.add(new Paragraph("asdsad: " + xd))
            documento.close();
            JOptionPane.showMessageDialog(null, "El archivo pdf fue creado correctamente");
        }
        else{
            JOptionPane.showMessageDialog(null, "Llenar los campos");    
        }
    }
    
    public void abrir(String nombre){
        try {
            File path = new File(nombre + ".pdf");
            Desktop.getDesktop().open(path);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex,"atencion",2);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel9 = new javax.swing.JLabel();
        secuencialRadioiButton = new javax.swing.JRadioButton();
        paraleloRadioButton = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        panelPlaneamiento = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        tiempoTotalParaleloTextField = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        buttonGroup1.add(secuencialRadioiButton);
        buttonGroup1.add(paraleloRadioButton);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("EVALUACIÓN INICIAL ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 50));

        secuencialRadioiButton.setText("Secuencial");
        secuencialRadioiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secuencialRadioiButtonActionPerformed(evt);
            }
        });
        getContentPane().add(secuencialRadioiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        paraleloRadioButton.setSelected(true);
        paraleloRadioButton.setText("Paralelo");
        paraleloRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paraleloRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(paraleloRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 92, -1));

        jPanel3.setLayout(new java.awt.CardLayout());

        panelPlaneamiento.setBorder(javax.swing.BorderFactory.createTitledBorder("Planeamiento Paralelo / Regla 1/5"));
        panelPlaneamiento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("Tiempo Asignado:");
        panelPlaneamiento.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 130, 20));

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        panelPlaneamiento.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 40, -1));

        jLabel12.setText("Analisis de la mision");
        panelPlaneamiento.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 133, 20));

        jLabel13.setText("Elaboracion de los cursos");
        panelPlaneamiento.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 155, 20));

        jLabel14.setText("Total Tiempo");
        panelPlaneamiento.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 106, 20));
        panelPlaneamiento.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 60, -1));
        panelPlaneamiento.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 60, -1));

        jTextField15.setText("20%");
        panelPlaneamiento.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 90, -1));

        jLabel15.setText("Etapas y pasos del PMTD");
        panelPlaneamiento.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel16.setText("% Planeamiento");
        panelPlaneamiento.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 100, -1));

        jLabel17.setText("En horas");
        panelPlaneamiento.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

        jTextField16.setText("30%");
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        panelPlaneamiento.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 90, 22));
        panelPlaneamiento.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 60, -1));

        jTextField18.setText("100%");
        panelPlaneamiento.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 90, -1));

        jLabel18.setText("Organizaciones a integrar");
        panelPlaneamiento.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 158, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Si", "No" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        panelPlaneamiento.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 90, -1));

        jLabel19.setText("Reducir el PMTD");
        panelPlaneamiento.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 106, 20));
        panelPlaneamiento.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 260, 40));

        jLabel24.setText("Dias");
        panelPlaneamiento.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, 20));
        panelPlaneamiento.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 60, -1));

        jLabel25.setText("Horas");
        panelPlaneamiento.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, 20));

        jTextField23.setText("30%");
        panelPlaneamiento.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 90, -1));

        jTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField24ActionPerformed(evt);
            }
        });
        panelPlaneamiento.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 60, -1));

        jTextField25.setText("20%");
        panelPlaneamiento.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 90, -1));
        panelPlaneamiento.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 60, -1));

        jLabel26.setText("Analisis /Comparacion");
        panelPlaneamiento.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 155, 20));

        jLabel27.setText("Desarrollo del plan");
        panelPlaneamiento.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 155, 20));
        panelPlaneamiento.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 70, -1));
        panelPlaneamiento.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 70, -1));
        panelPlaneamiento.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 70, -1));
        panelPlaneamiento.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 70, -1));

        jTextField31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField31ActionPerformed(evt);
            }
        });
        panelPlaneamiento.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 70, -1));

        jLabel28.setText("Tiempo Total Disponible");
        panelPlaneamiento.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, 20));

        tiempoTotalParaleloTextField.setText("112");
        tiempoTotalParaleloTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempoTotalParaleloTextFieldActionPerformed(evt);
            }
        });
        panelPlaneamiento.add(tiempoTotalParaleloTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 40, -1));

        jLabel29.setText("Dias");
        panelPlaneamiento.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, 20));

        jButton3.setText("Calcular");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panelPlaneamiento.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 150, 50));

        jLabel34.setText("Tiempo Acumulado ");
        panelPlaneamiento.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, 30));

        jLabel35.setText("En días");
        panelPlaneamiento.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        jPanel3.add(panelPlaneamiento, "card3");
        panelPlaneamiento.getAccessibleContext().setAccessibleName("");
        panelPlaneamiento.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, 530, 400));

        jButton2.setText("Generar informe");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        jButton6.setText("Abrir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void paraleloRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paraleloRadioButtonActionPerformed
        cocientePlaneamiento = 5;
        panelPlaneamiento.setBorder(javax.swing.BorderFactory.createTitledBorder("Planeamiento Paralelo / Regla 1/5"));
    }//GEN-LAST:event_paraleloRadioButtonActionPerformed

    private void secuencialRadioiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secuencialRadioiButtonActionPerformed
        cocientePlaneamiento = 3;
        panelPlaneamiento.setBorder(javax.swing.BorderFactory.createTitledBorder("Planeamiento Secuencial / Regla 1/3"));
    }//GEN-LAST:event_secuencialRadioiButtonActionPerformed

    private void tiempoTotalParaleloTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempoTotalParaleloTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiempoTotalParaleloTextFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Generar(nombre);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GuiaIni.class.getName()).log(Level.SEVERE, null,ex);
        } catch (DocumentException ex) {
            Logger.getLogger(GuiaIni.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField24ActionPerformed

    private void jTextField31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField31ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DecimalFormatSymbols separadoresPersonalizados = new DecimalFormatSymbols();
        separadoresPersonalizados.setDecimalSeparator('.');

        DecimalFormat formato1 = new DecimalFormat("#.00", separadoresPersonalizados);
        
        float diasA = Float.parseFloat(tiempoTotalParaleloTextField.getText());
        diasA=(diasA/cocientePlaneamiento);
        float diasAM= (diasA*3)/10;
        float diasAE= (diasA*2)/10;
        float diasH = diasA*24;
        float diasAMH= diasAM*24;
        float diasAEH= diasAE*24;
        String diasAC = formato1.format(diasA);
        String diasHC = formato1.format(diasH);
        String diasAMC = formato1.format(diasAM);
        String diasAMCH = formato1.format(diasAMH);
        String diasAEC = formato1.format(diasAE);
        String diasAECH = formato1.format(diasAEH);
        jTextField12.setText(diasAC);
        jTextField22.setText(diasHC);
        jTextField13.setText(diasAMC);
        jTextField26.setText(diasAMC);
        jTextField28.setText(diasAMCH);
        jTextField30.setText(diasAMCH);
        jTextField24.setText(diasAEC);
        jTextField17.setText(diasAEC);
        jTextField31.setText(diasAECH);
        jTextField27.setText(diasAECH);
        jTextField14.setText(diasAC);
        jTextField29.setText(diasHC);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(!nombre.isEmpty())
            abrir(nombre);
        else
            JOptionPane.showMessageDialog(null, "no se encuentra ese archivo con ese nombre","Atencion",2);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(evaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(evaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(evaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(evaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                evaInicial dialog = new evaInicial(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JPanel panelPlaneamiento;
    private javax.swing.JRadioButton paraleloRadioButton;
    private javax.swing.JRadioButton secuencialRadioiButton;
    private javax.swing.JTextField tiempoTotalParaleloTextField;
    // End of variables declaration//GEN-END:variables
}
