/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PMTD;

import Herramientas.HelpContainers;
import PDF.GuiaIniciacion;
import PDF.PDF_Generator;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author WIMBER
 */
public class GuiaIni extends javax.swing.JDialog {

    /**
     * Creates new form GuiaIni
     */
    String nombre = "Guia";
    int tiempoInicial = 0;
    public GuiaIni(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void setValoresIniciales(String tiempoInicial,DefaultComboBoxModel modeloPLaneamiento, int indexPlaneamiento){
        HelpContainers.setListaComboBox(metodo, modeloPLaneamiento, indexPlaneamiento);
        HelpContainers.setValorTextField(time, tiempoInicial);
    }
    
    

     public void Generar(String nombre) throws FileNotFoundException, DocumentException{
        if(!(Coord.getText().isEmpty() || (Trab.getText().isEmpty()) || (Mov.getText().isEmpty()) || (Req.getText().isEmpty()))){
            FileOutputStream archivo = new FileOutputStream(nombre + ".pdf"); 
            Document documento = new Document();
            PdfWriter.getInstance(documento, archivo);
            documento.open();
            
            Paragraph parrafo = new Paragraph("GUIA DE INICIACIÓN \n\n");
            parrafo.setAlignment(1);
            documento.add(parrafo);
            String id=IniciarDiseño.getSelectedItem().toString();
            documento.add(new Paragraph("1. Asignación del tiempo inicial: \n" + "    " + time.getText() + "\n"));
            documento.add(new Paragraph("2. Método de planeamiento: \n" + "    " + metodo.getSelectedItem().toString() + "\n"));
            documento.add(new Paragraph("3. Iniciar el diseño: \n" + "    " + id + "\n"));
            documento.add(new Paragraph("4. Coordinaciones por realizar: \n" + "    " + Coord.getText() + "\n"));
            documento.add(new Paragraph("5. Movimientos autorizados de reconocimiento y vigilancia: \n" + "    " + Mov.getText() + "\n"));
            documento.add(new Paragraph("6. Trabajos o tareas adicionales para el EM: \n" + "    -" + Trab.getText() + "\n"));
            documento.add(new Paragraph("7. Requerimientos de información: \n" + "    " + Req.getText() + "\n"));
            documento.add(new Paragraph("8. Lugar de planeamiento: \n" + "    " + lugar.getText() + "\n"));
            documento.add(new Paragraph("9. Fecha de planeamiento: \n" + "    " + fecha.getText() + "\n"));
            //documento.add(new Paragraph("asdsad: " + xd))
            documento.close();
            JOptionPane.showMessageDialog(null, "El archivo pdf fue creado correctamente");
        }
        else{
            JOptionPane.showMessageDialog(null, "Llenar los campos");    
        }
    }
    
    public void abrir(String nombre){
        try {
            File path = new File(nombre + ".pdf");
            Desktop.getDesktop().open(path);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex,"atencion",2);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane7 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        IniciarDiseño = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        Coord = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Mov = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Trab = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        Req = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        time = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        metodo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        fecha = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lugar = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("GUIA DE INICIACIÓN");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 40));

        jButton1.setText("Generar PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 1070, -1, -1));

        jButton2.setText("Abrir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 1070, -1, -1));

        jLabel1.setText("Iniciar el diseño:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 30));

        jLabel2.setText("Coordinaciones por realizar:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        IniciarDiseño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        IniciarDiseño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarDiseñoActionPerformed(evt);
            }
        });
        jPanel1.add(IniciarDiseño, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 40, 30));

        jScrollPane3.setToolTipText("");

        Coord.setColumns(20);
        Coord.setLineWrap(true);
        Coord.setRows(5);
        jScrollPane3.setViewportView(Coord);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 630, 120));

        jLabel3.setText("Movimientos autorizados de reconocimiento y vigilancia: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 20));

        Mov.setColumns(20);
        Mov.setLineWrap(true);
        Mov.setRows(5);
        Mov.setText("- Todos los movimientos se realizarán con orden y de preferencia en horas de oscuridad.\n- G-2 realizar el análisis del espectro electromagnético.\n- reconocimiento de rutas principales y alternas, aptas para el desplazamiento de nuestras fuerzas.\n- coordinar, con el escalón superior el resultado del cruce de los vectores que convergen en nuestra ADR.\n- G-2, G-3 y G-4, coordinar el plan de desplazamiento.\n- bases contraterroristas, realizar reconocimientos de sectores y de rutas.\n- G-5, G-2 y G-3 coordinar con entidades civiles y articular esfuerzos en nuestra ADR.\n- G-2 orientar su esfuerzo de búsqueda, mediante sus planes de inteligencia distribuidos en el sector.");
        jScrollPane1.setViewportView(Mov);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 630, 120));

        jLabel4.setText("Trabajos o tareas adicionales para el EM:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        Trab.setColumns(20);
        Trab.setLineWrap(true);
        Trab.setRows(5);
        Trab.setText("- G-1: Dar cuenta de la situación de personal con respecto a  contagiados con COVID de las UU.\n- G-2: Intensificar las medidas de contrainteligencia para  proteger la información pertinente de nuestras  operaciones y acciones militares.\n- G-3: Intensificar el entrenamiento y ensayos nocturnos para las operaciones militares.\n- G-4: Solicitar al escalón superior el completamiento de las necesidades para cumplir con las acciones militares.\n- G-5: Realizar en coordinación con los demás miembros del  em, el planeamiento para las acciones militares.");
        jScrollPane2.setViewportView(Trab);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 630, 120));

        Req.setColumns(20);
        Req.setLineWrap(true);
        Req.setRows(5);
        Req.setText("- Información detallada de las poblaciones con  mayor vulnerabilidad en el ADR.\n- Últimos movimientos de la OT-SL dentro de nuestra ADR.\n- Lugares probables para instalación de albergues temporales.\n- Capacidad operativa del material y equipo.\n- Información sobre puentes en el ADR.\n- Apoyo administrativo con lo que contamos.");
        jScrollPane4.setViewportView(Req);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 630, 120));

        jLabel5.setText("Requerimientos de información:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, -1, -1));

        jLabel6.setText("Días");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, 30));

        time.setText("112");
        time.setEnabled(false);
        time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeActionPerformed(evt);
            }
        });
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 40, 30));

        jLabel7.setText("Método de planeamiento:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, 30));

        metodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paralelo", "Secuencial" }));
        metodo.setEnabled(false);
        metodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metodoActionPerformed(evt);
            }
        });
        jPanel1.add(metodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 120, 30));

        jLabel10.setText("Fecha de planeamiento");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 740, -1, -1));

        fecha.setColumns(20);
        fecha.setLineWrap(true);
        fecha.setRows(5);
        fecha.setText("1. D-112 (recepción de la misión)\n2. D-105 (análisis de la misión)\n3. D-101 (desarrollo del CONOPs)\n4. D-94 (decisión del CMDTE)\n5. D-91 (distribución de la orden de operaciones a las UU subordinadas)");
        jScrollPane6.setViewportView(fecha);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 760, 630, 120));

        jLabel11.setText("Asignacion del tiempo inicial:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 30));

        lugar.setColumns(20);
        lugar.setLineWrap(true);
        lugar.setRows(5);
        lugar.setText("Se reunirán en la sala de operaciones del puesto de comando de la 2° BRIG INF que se encuentra en la localidad de Pichari bajo a partir del día (D-112) según lo especificado por el jema y en situaciones especiales con orden.");
        jScrollPane5.setViewportView(lugar);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 920, 630, 120));

        jLabel8.setText("Lugar de planeamiento");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 900, -1, -1));

        jScrollPane7.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
              PDF_Generator.GenerarGuiaIniciacion("Guia de iniciacion",
                    new GuiaIniciacion(Integer.parseInt(time.getText()), (String)IniciarDiseño.getSelectedItem(),
                            (String) metodo.getSelectedItem(), Coord.getText(), Mov.getText(), 
                            Trab.getText(), Req.getText(), fecha.getText(), lugar.getText()) );
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GuiaIni.class.getName()).log(Level.SEVERE, null,ex);
        } catch (DocumentException ex) {
            Logger.getLogger(GuiaIni.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(!"Guia de iniciacion".isEmpty())
            abrir("Guia de iniciacion");
        else
            JOptionPane.showMessageDialog(null, "no se encuentra ese archivo con ese nombre","Atencion",2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void IniciarDiseñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarDiseñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IniciarDiseñoActionPerformed

    private void timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeActionPerformed

    private void metodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_metodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiaIni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiaIni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiaIni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiaIni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GuiaIni dialog = new GuiaIni(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Coord;
    private javax.swing.JComboBox<String> IniciarDiseño;
    private javax.swing.JTextArea Mov;
    private javax.swing.JTextArea Req;
    private javax.swing.JTextArea Trab;
    private javax.swing.JTextArea fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea lugar;
    private javax.swing.JComboBox<String> metodo;
    private javax.swing.JTextField time;
    // End of variables declaration//GEN-END:variables
}
